name: Deployment to AWS
on:
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy static files to AWS S3
        id: aws-deploy-s3
        uses: oneyedev/aws-deploy-s3@v2
        with:
          region: us-east-1
          bucket: www.cormac.is
          source: ''
          target: ''
